---
- name: build new machine
  hosts: builder
  become: yes
  gather_facts: no
  serial: 1
  roles: 
  - role: libvirt-guest
    delegate_to: hypervisor

  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30
    become: no

