---
- name: build new machine
  hosts: builder
  become: yes
  gather_facts: no
  serial: 1
  vars_files:
  - vault.yml

  roles: 
  - role: libvirt-guest
    delegate_to: "{{ groups['hypervisor'][0] }}"

  tasks:
  - name: Wait for new server to be ready
    ansible.builtin.wait_for_connection:
      timeout: 30
      #timeout: 180
    become: no

