# incomplete
# gitlab?
# https://hardiman.consulting/ansible/2.11/git-set-up/git-repo-shared.html

- name: build the image builder
  hosts: builder
  become: yes
  gather_facts: no
  tasks: 

  # modularity 'container-tools' provides commands 'skopeo', 'podman', and more
  - name: install container packages
    ansible.builtin.dnf:
      name: '@container-tools:rhel8'
      state: present
    register: r_dnf_container

  # !!! some duplicated in group_vars/builder/main.yml
  # package 'lorax' provides command 'mkksiso'
  # package 'weldr-client' provides command 'composer-cli'
  - name: install image builder packages
    ansible.builtin.dnf:
      name: 
        - cockpit-composer
        - git
        - lorax
        - osbuild-composer
        - weldr-client
      state: latest
    register: r_dnf_builder

  - name: start the server
    ansible.builtin.systemd:
      name: osbuild-composer.socket
      state: started
      enabled: yes

