- name: install container tools
  ansible.builtin.import_playbook: container-host.yml

- name: install image builder service
  ansible.builtin.import_playbook: image-builder.yml

- name: install CA certificate
  ansible.builtin.import_playbook: ca.yml



