- name: install container tools
  ansible.builtin.import_playbook: container-host.yml

- name: install image builder service
  ansible.builtin.import_playbook: image-builder.yml

- name: create and install a CA certificate
  ansible.builtin.import_playbook: cert-ca.yml

- name: create a server certificate
  ansible.builtin.import_playbook: cert-server.yml

- name: install the server certificate
  ansible.builtin.import_playbook: cert-cockpit.yml

# How about ansible? 
# This is a RHEL 8 machine. Could be handy.
# # subscription-manager repos --enable ansible-automation-platform-2.2-for-rhel-8-x86_64-rpms
# dnf install ansible-core ansible-navigator ansible-builder
#


